# Site settings
title:          Matt Heaton
tagline:        'Agricultural Development · Sustainability · Data Visualisation'
description:    'Research Fellow at the University of East Anglia.'
url:            'https://sheenless.github.io'
baseurl:        ''

# Author
author:  
  name:         'Matt Heaton'

# Build settings
markdown:       kramdown
highlighter:    rouge
paginate:       5

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-seo-tag